sudo: required
dist: trusty
language: python
python:
    - '3.6'

install:
    - pip3 install -r requirements.txt
    - pip3 install -r test-requirements.txt
    - pip3 install -r faucet/test-requirements.txt
script:
    - "python3 -m pytest --cov=. tests/"
